name: CodinGame code test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Repo check
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./Task-4/tests/cd-tests.sh

      - name: Run the script
        run: ./Task-4/tests/cd-tests.sh