name: Manual Message Workflow

on:
  workflow_dispatch:

jobs:
  show-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./hello.sh

      - name: Run the script
        run: ./hello.sh
